"""
train_cnn.py

Trains the Tiny 1D CNN fall-detector on labeled IMU windows (Fall vs.
everything else, including the hard-negative motions from the generator),
quantizes it to INT8, and exports it as a C array for TFLite Micro.

Requires: tensorflow (pip install tensorflow --break-system-packages)

Model is deliberately small (<= 2 Conv1D layers, <= 16 filters) to keep the
TFLite Micro tensor arena in the tens-of-KB range on ESP32 (per spec §9).

Usage:
    python train_cnn.py --imu ../data/imu_50hz.csv --out ../models
"""

import argparse
import os
import numpy as np
import pandas as pd

WINDOW_S = 4.0
IMU_FS = 50
WINDOW_LEN = int(WINDOW_S * IMU_FS)  # 200 samples
N_CHANNELS = 6  # acc_x,y,z, gyro_x,y,z

POSITIVE_LABEL = "Fall"


def build_cnn_dataset(imu_df):
    """Every segment becomes exactly one fixed-length window (segments were generated
    at WINDOW_S duration for Fall/HardNeg; longer activity segments are randomly
    sub-windowed so the CNN also sees plenty of true negatives)."""
    X, y = [], []
    rng = np.random.default_rng(0)

    for seg_id, seg in imu_df.groupby("seg_id"):
        label = seg["label"].iloc[0]
        cols = ["acc_x", "acc_y", "acc_z", "gyro_x", "gyro_y", "gyro_z"]
        arr = seg[cols].to_numpy()
        n = len(arr)

        if label == POSITIVE_LABEL:
            if n >= WINDOW_LEN:
                X.append(arr[:WINDOW_LEN])
                y.append(1)
        elif label.startswith("HardNeg") or label == "Transition":
            if n >= WINDOW_LEN:
                X.append(arr[:WINDOW_LEN])
                y.append(0)
        else:
            # normal activity segment: sample a few random true-negative windows from it
            if n >= WINDOW_LEN:
                n_samples = max(1, n // (WINDOW_LEN * 4))
                for _ in range(n_samples):
                    start = rng.integers(0, n - WINDOW_LEN + 1)
                    X.append(arr[start:start + WINDOW_LEN])
                    y.append(0)

    X = np.stack(X).astype(np.float32)
    y = np.array(y, dtype=np.int32)
    return X, y


def normalize(X, mean=None, std=None):
    if mean is None:
        mean = X.reshape(-1, X.shape[-1]).mean(axis=0)
        std = X.reshape(-1, X.shape[-1]).std(axis=0) + 1e-6
    Xn = (X - mean) / std
    return Xn, mean, std


def build_model():
    import tensorflow as tf
    from tensorflow.keras import layers, models

    model = models.Sequential([
        layers.Input(shape=(WINDOW_LEN, N_CHANNELS)),
        layers.Conv1D(12, kernel_size=7, strides=2, activation="relu"),   # 200 -> 97
        layers.Conv1D(16, kernel_size=5, strides=2, activation="relu"),   # 97 -> 47
        layers.GlobalAveragePooling1D(),
        layers.Dense(16, activation="relu"),
        layers.Dense(1, activation="sigmoid"),
    ])
    model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy", tf.keras.metrics.Recall(name="recall")])
    return model


def representative_dataset_gen(X_train):
    def gen():
        for i in range(min(200, len(X_train))):
            yield [X_train[i:i + 1].astype(np.float32)]
    return gen


def quantize_int8(model, X_train, out_path):
    import tensorflow as tf
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset_gen(X_train)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    tflite_model = converter.convert()
    with open(out_path, "wb") as f:
        f.write(tflite_model)
    return tflite_model


def tflite_to_c_array(tflite_bytes, var_name="fall_model_data"):
    lines = []
    lines.append("// Auto-generated by train_cnn.py -- DO NOT EDIT BY HAND")
    lines.append("#ifndef FALL_MODEL_DATA_H")
    lines.append("#define FALL_MODEL_DATA_H")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append(f"alignas(8) const unsigned char {var_name}[] = {{")
    hex_bytes = [f"0x{b:02x}" for b in tflite_bytes]
    for i in range(0, len(hex_bytes), 12):
        lines.append("  " + ", ".join(hex_bytes[i:i + 12]) + ",")
    lines.append("};")
    lines.append(f"const unsigned int {var_name}_len = {len(tflite_bytes)};")
    lines.append("")
    lines.append("#endif // FALL_MODEL_DATA_H")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--imu", type=str, default="../data/imu_50hz.csv")
    ap.add_argument("--out", type=str, default="../models")
    ap.add_argument("--epochs", type=int, default=25)
    args = ap.parse_args()

    imu_df = pd.read_csv(args.imu)
    X, y = build_cnn_dataset(imu_df)
    print(f"Windows: {len(X)}  (positive falls: {y.sum()}, negatives: {len(y) - y.sum()})")
    if y.sum() < 5:
        raise SystemExit("Not enough Fall examples -- generate more dummy data (increase --minutes).")

    Xn, mean, std = normalize(X)

    # Stratified split: with very few positive (Fall) examples, a plain random shuffle
    # can easily place too few -- or zero -- falls in the test set by chance, making the
    # recall metric meaningless. Splitting the positive and negative indices separately
    # guarantees both sets get a proportional share of falls.
    rng = np.random.default_rng(0)
    pos_idx = np.where(y == 1)[0]
    neg_idx = np.where(y == 0)[0]
    rng.shuffle(pos_idx)
    rng.shuffle(neg_idx)
    pos_split = max(1, int(0.8 * len(pos_idx)))  # at least 1 positive example in training
    neg_split = int(0.8 * len(neg_idx))
    train_idx = np.concatenate([pos_idx[:pos_split], neg_idx[:neg_split]])
    test_idx = np.concatenate([pos_idx[pos_split:], neg_idx[neg_split:]])
    rng.shuffle(train_idx)
    rng.shuffle(test_idx)
    print(f"Train falls: {len(pos_idx[:pos_split])}  Test falls: {len(pos_idx[pos_split:])}")

    X_train, y_train = Xn[train_idx], y[train_idx]
    X_test, y_test = Xn[test_idx], y[test_idx]

    model = build_model()
    model.fit(X_train, y_train, validation_data=(X_test, y_test),
              epochs=args.epochs, batch_size=32, verbose=2,
              class_weight={0: 1.0, 1: len(y_train) / (2 * max(1, y_train.sum()))})

    loss, acc, recall = model.evaluate(X_test, y_test, verbose=0)
    print(f"Test accuracy: {acc:.3f}  Test recall (fall): {recall:.3f}")

    os.makedirs(args.out, exist_ok=True)
    tflite_path = os.path.join(args.out, "fall_model.tflite")
    tflite_bytes = quantize_int8(model, X_train, tflite_path)
    print(f"Wrote {tflite_path} ({len(tflite_bytes)} bytes)")

    c_code = tflite_to_c_array(tflite_bytes)
    header_path = os.path.join(args.out, "fall_model_data.h")
    with open(header_path, "w") as f:
        f.write(c_code)
    print(f"Wrote {header_path}")

    # Save normalization constants for the firmware to replicate preprocessing
    norm_path = os.path.join(args.out, "fall_model_norm.h")
    with open(norm_path, "w") as f:
        f.write("// Auto-generated by train_cnn.py -- normalization constants (must match training)\n")
        f.write("#ifndef FALL_MODEL_NORM_H\n#define FALL_MODEL_NORM_H\n\n")
        f.write(f"static const float FALL_MODEL_MEAN[{N_CHANNELS}] = {{{', '.join(f'{v:.6f}f' for v in mean)}}};\n")
        f.write(f"static const float FALL_MODEL_STD[{N_CHANNELS}]  = {{{', '.join(f'{v:.6f}f' for v in std)}}};\n")
        f.write(f"#define FALL_MODEL_WINDOW_LEN {WINDOW_LEN}\n")
        f.write(f"#define FALL_MODEL_N_CHANNELS {N_CHANNELS}\n\n")
        f.write("#endif // FALL_MODEL_NORM_H\n")
    print(f"Wrote {norm_path}")


if __name__ == "__main__":
    main()