"""
train_decision_tree.py

Trains the activity-classification Decision Tree on engineered IMU features
(1-second windows) and exports it as a compact C header the ESP32 firmware
can compile directly (no runtime ML library needed for this stage).

Classes (per spec §6): Resting, Inactive, Walking, Running, Transition
Falls / hard-negatives are excluded here -- they belong to the CNN (see train_cnn.py).

Usage:
    python train_decision_tree.py --imu ../data/imu_50hz.csv --out ../models
"""

import argparse
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier, _tree

ACTIVITY_CLASSES = ["Resting", "Inactive", "Walking", "Running", "Transition"]
WINDOW_S = 1.0
IMU_FS = 50


def extract_window_features(acc, gyro):
    """acc, gyro: (n,3) arrays for a 1-second window. Returns feature dict matching spec §3/§7 of doc 1."""
    acc_mag = np.linalg.norm(acc, axis=1)
    gyro_mag = np.linalg.norm(gyro, axis=1)
    return {
        "acc_mag_mean": acc_mag.mean(),
        "gyro_mag_mean": gyro_mag.mean(),
        "acc_var": acc_mag.var(),
        "gyro_var": gyro_mag.var(),
        "movement_intensity": acc_mag.std() + gyro_mag.std(),
        "acc_peak": acc_mag.max(),
    }


def build_feature_table(imu_df):
    rows = []
    for seg_id, seg in imu_df.groupby("seg_id"):
        label = seg["label"].iloc[0]
        if label not in ACTIVITY_CLASSES:
            continue  # skip Fall / HardNeg segments -- not part of the activity tree
        acc = seg[["acc_x", "acc_y", "acc_z"]].to_numpy()
        gyro = seg[["gyro_x", "gyro_y", "gyro_z"]].to_numpy()
        win_len = int(WINDOW_S * IMU_FS)
        for start in range(0, len(acc) - win_len + 1, win_len):
            f = extract_window_features(acc[start:start + win_len], gyro[start:start + win_len])
            f["label"] = label
            rows.append(f)
    return pd.DataFrame(rows)


FEATURE_NAMES = ["acc_mag_mean", "gyro_mag_mean", "acc_var", "gyro_var", "movement_intensity", "acc_peak"]


def tree_to_c(tree, feature_names, class_names, func_name="classify_activity"):
    """Convert a fitted sklearn DecisionTreeClassifier into a C function of nested if/else."""
    t = tree.tree_
    lines = []
    lines.append(f"// Auto-generated by train_decision_tree.py -- DO NOT EDIT BY HAND")
    lines.append(f"#ifndef ACTIVITY_TREE_H")
    lines.append(f"#define ACTIVITY_TREE_H")
    lines.append("")
    lines.append("typedef struct { int label; float confidence; } activity_result_t;")
    lines.append("")
    lines.append("typedef enum {")
    for i, c in enumerate(class_names):
        lines.append(f"    ACTIVITY_{c.upper()} = {i},")
    lines.append("} activity_t;")
    lines.append("")
    lines.append(f"static activity_result_t {func_name}(const float feat[{len(feature_names)}]) {{")
    lines.append(f"    // feature order: {', '.join(feature_names)}")

    def recurse(node, depth):
        indent = "    " * (depth + 1)
        if t.feature[node] != _tree.TREE_UNDEFINED:
            fname = feature_names[t.feature[node]]
            fidx = feature_names.index(fname)
            threshold = t.threshold[node]
            lines.append(f"{indent}if (feat[{fidx}] <= {threshold:.6f}f) {{")
            recurse(t.children_left[node], depth + 1)
            lines.append(f"{indent}}} else {{")
            recurse(t.children_right[node], depth + 1)
            lines.append(f"{indent}}}")
        else:
            counts = t.value[node][0]
            majority = int(np.argmax(counts))
            purity = float(counts[majority] / counts.sum())
            lines.append(f"{indent}return (activity_result_t){{ .label = ACTIVITY_{class_names[majority].upper()}, .confidence = {purity:.4f}f }};")

    recurse(0, 0)
    lines.append("}")
    lines.append("")
    lines.append("#endif // ACTIVITY_TREE_H")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--imu", type=str, default="../data/imu_50hz.csv")
    ap.add_argument("--out", type=str, default="../models")
    ap.add_argument("--max_depth", type=int, default=6)
    args = ap.parse_args()

    imu_df = pd.read_csv(args.imu)
    feat_df = build_feature_table(imu_df)
    if feat_df.empty:
        raise SystemExit("No activity windows found -- generate more dummy data first (increase --minutes).")

    X = feat_df[FEATURE_NAMES].to_numpy()
    y = feat_df["label"].to_numpy()

    present_classes = sorted(feat_df["label"].unique(), key=lambda c: ACTIVITY_CLASSES.index(c))

    clf = DecisionTreeClassifier(max_depth=args.max_depth, min_samples_leaf=20, random_state=42)
    clf.fit(X, y)

    train_acc = clf.score(X, y)
    print(f"Windows used: {len(feat_df)}")
    print(f"Classes present: {present_classes}")
    print(f"Training accuracy: {train_acc:.3f}  (offline sanity check -- do a proper train/test split for real evaluation)")

    class_names_ordered = list(clf.classes_)
    c_code = tree_to_c(clf, FEATURE_NAMES, class_names_ordered)

    import os
    os.makedirs(args.out, exist_ok=True)
    out_path = os.path.join(args.out, "activity_tree.h")
    with open(out_path, "w") as f:
        f.write(c_code)
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
