"""
Single-slot coordinator for the local llama.cpp box (the speaking model).

The local box at `local_api_base` can only process ONE request quickly at a time.
Speaking to the user is always top priority, so any BACKGROUND work running on the
box (summarization, vision/image analysis, deferred tool follow-ups) must abort the
instant the user speaks — that keeps time-to-first-sentence minimal.

How aborting works (no llama.cpp code change needed): we simply close the HTTP
connection of the in-flight background request. llama-server detects the client
disconnect and stops generating, freeing the slot immediately.

Public API:
    preempt_background()                         -> kill any running background task NOW
    generate_background(messages, image_b64=...) -> blocking text gen, abortable, returns str|None
    iter_sse(resp)                               -> parse OpenAI SSE 'data:' dicts
    post_stream(messages, ...)                   -> low-level streaming POST (used by the speaking path)
    update_speaking_prefix(messages)             -> register the speaking convo prefix for re-warming
    note_speaking(active)                        -> mark a speaking request in flight
    rewarm()                                     -> re-prime the KV cache with the speaking prefix

Cache re-warm: the box has ONE fast slot, so any background request (summary,
summary, vision) evicts the speaking conversation's KV-cache prefix. After EVERY
background request finishes (or is preempted), we automatically re-send the speaking
prefix — ending with the last assistant reply for assistant-prefill caching — with
max_tokens=1, so the user's conversation is hot again before they next speak.
"""

import hashlib
import http.client
import json
import re
import socket
import threading
import time
from urllib.parse import urlparse

import requests

from tools_and_config.config_loader import get_llm_config

_cfg = get_llm_config()
BASE = _cfg.get("local_api_base", "http://100.64.0.10:8080/v1").rstrip("/")
URL = f"{BASE}/chat/completions"
_PARSED = urlparse(BASE)
_HOST = _PARSED.hostname or "127.0.0.1"
_PORT = _PARSED.port or (443 if _PARSED.scheme == "https" else 80)
_PATH = f"{_PARSED.path.rstrip('/')}/chat/completions"
MODEL = _cfg.get("local_model", "kiki-local")
DEFAULT_TEMP = _cfg.get("temperature", 1.0)
_REWARM_ENABLED = _cfg.get("rewarm_after_background", True)
# Whether the CLIENT re-warms after a SPEAKING turn. When the box runs
# --prefill-after-response it already prefills the reply server-side after each
# generation, so the client rewarm would just duplicate that work (a second
# ~2-4s pass on the single slot). Set False to let the server own the
# post-speaking prefill; the client still rewarms after BACKGROUND work (which
# evicts the speaking prefix) and after IDLE injections (which the server has no
# knowledge of) — those are gated by _REWARM_ENABLED, not this flag.
_REWARM_AFTER_SPEAKING = _cfg.get("rewarm_after_speaking", True)
# Tokens GENERATED by a rewarm request. The point of a rewarm is the PREFILL
# (loading the convo prefix into KV cache); generated tokens are discarded but
# keep the slot busy (~64ms each), so keep this at 1 for pure prefill.
# IMPORTANT: On SWA models, any generated tokens during rewarm create a cache
# state that differs from the next real request → context invalidation. Using 1
# ensures the rewarm is truly prefill-only.
_REWARM_MAX_TOKENS = _cfg.get("rewarm_max_tokens", 1)

# Per-request override that re-enables thinking on a server launched with
# --reasoning-budget 0. chat_template_kwargs is the upstream llama-server
# mechanism; if this build prefers a different field (e.g. "reasoning_budget": -1),
# this is the one place to change it.
REASONING_OVERRIDE_FIELDS = {"chat_template_kwargs": {"enable_thinking": True}}

# The server runs reasoning_format=none, so thinking arrives inline in content.
# gemma-4 uses <|channel>thought ... <channel|> markers; older models use <think>.
_THINK_BLOCK_RE = re.compile(
    r"<think(?:ing)?>.*?</think(?:ing)?>"
    r"|<\|channel>\s*thought\b.*?<channel\|>",
    re.DOTALL | re.IGNORECASE)
_THINK_OPEN_RE = re.compile(
    r"(?:<think(?:ing)?>|<\|channel>\s*thought\b).*\Z",
    re.DOTALL | re.IGNORECASE)

# Keep-alive session shared by all callers (avoids per-request TCP/TLS handshakes).
SESSION = requests.Session()

# --- Background coordination ---
_bg_lock = threading.Lock()           # serializes background tasks among themselves
_bg_abort = threading.Event()         # set => current background task should bail
_bg_active = threading.Event()        # a background task is currently in flight
# The in-flight http.client connection. Unlike a requests Response (which only
# exists once the server sends HEADERS — i.e. AFTER the whole prefill on
# llama-server), the raw connection's socket exists from the moment we POST,
# so preempt can kill a background request even mid-prefill.
_bg_current = {"conn": None}

# --- Speaking-prefix registry (for cache re-warming) ---
_speaking_prefix = {"messages": None}  # normalized speaking conversation prefix
_speaking_active = threading.Event()   # a SPEAKING request is in flight right now
# Rewarm coalescing. At most one worker runs at a time; a prefix change that
# arrives while it is mid-flight sets _rewarm_dirty (NOT dropped) so the worker
# re-warms the LATEST prefix before exiting. Guarded by _rewarm_lock — the old
# single-Event coalescer silently dropped the in-flight update, leaving the box
# warm for a STALE prefix (e.g. after a summarize swap), so the next turn paid a
# full re-prefill from the divergence point (16s TTFW, f_keep ~0.37).
_rewarm_lock = threading.Lock()
_rewarm_running = False                 # a rewarm worker thread is active
_rewarm_dirty = False                   # prefix moved since the worker last read it

# --- Conversation protection ---
# gemma-4 is an SWA model: ANY different prompt occupying the single slot
# invalidates the speaking conversation's KV cache AND its context checkpoints
# ("forcing full prompt re-processing"), so the next voice turn pays a full
# ~40s prefill. While the conversation is HOT (user active within this window),
# the box is reserved for speaking: background requests are refused here and
# generate_llm_resp's fallback chain reroutes them to the cloud instead.
_PROTECT_S = _cfg.get("protect_conversation_seconds", 180)
_last_user_activity = {"t": 0.0}



def note_user_activity():
    """Mark the conversation hot (hotword / user speech / speaking turn)."""
    _last_user_activity["t"] = time.time()


def conversation_hot() -> bool:
    return (time.time() - _last_user_activity["t"]) < _PROTECT_S


def preempt_background():
    """Abort any in-flight background request immediately (called by the speaking
    path / on a new user request) so the box is free to answer the user.

    NEVER blocks the caller (this runs on the hotword thread — a blocking close
    here once delayed mic unmute by ~8s). The socket shutdown happens in a
    throwaway daemon thread; llama-server frees the slot on disconnect, even
    mid-prefill."""
    if not _bg_active.is_set():
        return
    _bg_abort.set()
    conn = _bg_current.get("conn")
    if conn is not None:
        def _kill(c):
            try:
                if c.sock is not None:
                    c.sock.shutdown(socket.SHUT_RDWR)
            except Exception:
                pass
            try:
                c.close()
            except Exception:
                pass
        threading.Thread(target=_kill, args=(conn,), daemon=True).start()
    print("[LocalLLM] ⏹ Preempted background task for user request.")


# Hash of the prefix that is currently warm in the box's KV cache (set by a
# completed rewarm, cleared whenever any other prompt lands on the slot). Lets
# schedule_rewarm() skip redundant rewarms — re-prefilling an already-warm
# prefix wastes the slot for the full prefill duration right when the user is
# most likely to speak (e.g. just after the wake word).
_warm_prefix_hash = {"value": None}


def _prefix_hash(messages) -> str:
    try:
        return hashlib.md5(
            json.dumps(messages, sort_keys=True, ensure_ascii=False).encode()
        ).hexdigest()
    except Exception:
        return str(time.time())  # unhashable → always treated as cold


def update_speaking_prefix(normalized_messages):
    """Register the speaking conversation's normalized message prefix so rewarm()
    can re-prime the KV cache after background work. Called by the speaking path
    (core/llm.py) after each turn and by warmup() at startup."""
    _speaking_prefix["messages"] = list(normalized_messages)


def rewarm_after_speaking_enabled() -> bool:
    """True if the CLIENT should rewarm after a speaking turn. False = the box's
    --prefill-after-response owns the post-reply prefill (no duplicate client pass)."""
    return _REWARM_AFTER_SPEAKING


def mark_prefix_warm():
    """Record the current speaking prefix as already warm WITHOUT a client rewarm.

    Used after a speaking turn when --prefill-after-response prefills the reply
    server-side — the client rewarm would duplicate it. Safe: any later
    background request clears this hash (line in generate_background), so
    background-eviction recovery still rewarms; and any prefix change (an idle
    injection) won't match this hash, so those still rewarm."""
    prefix = _speaking_prefix["messages"]
    if prefix:
        _warm_prefix_hash["value"] = _prefix_hash(prefix)


def note_speaking(active: bool):
    """Mark that a speaking request is in flight. While set, auto-rewarm is
    skipped — the speaking request itself reloads the cache (and the server's
    --prefill-after-response caches the reply tokens)."""
    if active:
        _speaking_active.set()
        # The speaking request appends generated tokens to the slot — whatever
        # prefix was warm no longer matches byte-for-byte.
        _warm_prefix_hash["value"] = None
    else:
        _speaking_active.clear()


def rewarm():
    """Re-prime the box's KV cache with the speaking conversation prefix
    (prefill-only: max_tokens=1). Serialized on _bg_lock and preemptible like
    any background request. Skipped when this exact prefix is already warm."""
    prefix = _speaking_prefix["messages"]
    if not prefix:
        return
    h = _prefix_hash(prefix)
    if _warm_prefix_hash["value"] == h:
        print("[LocalLLM] 🔥 Rewarm skipped — prefix already warm in KV cache.")
        return
    print(f"[LocalLLM] 🔥 Re-warming speaking prefix ({len(prefix)} messages)...")
    generate_background(messages=prefix, max_tokens=_REWARM_MAX_TOKENS,
                        temperature=1.0, is_rewarm=True, rewarm_hash=h)


def prefill_partial(partial_user_text: str):
    """Incremental prefill of the user's words WHILE they are still speaking.

    Sends prefix + a user message holding the rolling partial transcript as a
    prefill-only request (max_tokens=1). The server keeps the common token
    prefix, so by the endpoint commit only the last few words' tokens remain
    to prefill — cutting the turn's TTFT from ~250ms (dense MoE expert read for
    a 15-20 token batch) to well under 100ms. Extending the warm prefix keeps
    it a byte-prefix of the real turn's request, so KV-cache rule 2 holds and
    _warm_prefix_hash stays valid (the prefix is still cached).

    Non-blocking: skipped when a prior background request still holds the lock
    (the next partial, ~1s later, catches up) or a speaking stream is active.
    """
    prefix = _speaking_prefix["messages"]
    if not prefix or not partial_user_text:
        return
    if _speaking_active.is_set() or _bg_lock.locked():
        return

    def _run():
        print(f"[LocalLLM] ⏩ Partial prefill ({len(partial_user_text)} chars)...")
        generate_background(
            messages=list(prefix) + [{"role": "user", "content": partial_user_text}],
            max_tokens=1, temperature=1.0, is_rewarm=True)

    threading.Thread(target=_run, daemon=True, name="partial-prefill").start()


def _rewarm_worker():
    """Warm the speaking prefix, then KEEP warming until the box holds the
    LATEST prefix. A prefix change mid-rewarm (summary swap, late injection)
    sets _rewarm_dirty; without this re-check that update was dropped by the
    coalescer and the box stayed warm for a stale prefix."""
    global _rewarm_running, _rewarm_dirty
    try:
        while True:
            rewarm()  # reads the CURRENT _speaking_prefix each call
            with _rewarm_lock:
                # Stop if nothing moved, or the user started talking (the
                # speaking path now owns the slot and prefills the latest itself).
                if not _rewarm_dirty or _speaking_active.is_set():
                    _rewarm_running = False
                    return
                _rewarm_dirty = False  # consume the update and warm again
    except BaseException:
        with _rewarm_lock:
            _rewarm_running = False
        raise


def schedule_rewarm():
    """Public: fire-and-forget rewarm. Called by the speaking path after each
    turn (client-side replacement for the server's --prefill-after-response:
    re-prefills the convo incl. the fresh assistant reply, ~15 new tokens)."""
    _schedule_rewarm()


def _schedule_rewarm():
    """Fire-and-forget rewarm after a background request or after speaking,
    coalesced to one ACTIVE worker and skipped while the user is being answered.

    After speaking: converts assistant reply tokens from generated into prefilled
    with proper SWA checkpoints, so the next turn gets a cache hit.
    After background work: re-primes the conversation prefix that was evicted.

    If a worker is already running, the request is NOT dropped: it marks the
    prefix dirty so the running worker re-warms the new prefix before exiting
    (fixes the lost-update race where a summarize swap left the box stale)."""
    global _rewarm_running, _rewarm_dirty
    if not _REWARM_ENABLED:
        return
    if not _speaking_prefix["messages"]:
        return
    if _speaking_active.is_set():
        return
    with _rewarm_lock:
        if _rewarm_running:
            _rewarm_dirty = True
            return
        _rewarm_running = True
    threading.Thread(target=_rewarm_worker, daemon=True).start()


def strip_thinking_blocks_only(text):
    """Remove only CLOSED thinking blocks (keeps an unclosed trailing one)."""
    return _THINK_BLOCK_RE.sub("", text) if text else text


def strip_thinking(text):
    """Remove inline thinking (server runs reasoning_format=none, so thinking
    tokens arrive in content): closed <think>/<|channel>thought blocks AND any
    unclosed trailing block."""
    if not text:
        return text
    text = _THINK_BLOCK_RE.sub("", text)
    text = _THINK_OPEN_RE.sub("", text)
    return text.strip()


def _emergency_trim_messages(messages, max_tokens=4500):
    """Trim a message list to fit within the context budget by dropping older
    middle messages. Keeps: first message (system prompt), last 2 messages
    (current exchange). Does NOT touch tool definitions/schemas.
    Returns the trimmed list or None if even the minimum can't fit."""
    from core.brain.token_counter import count_tokens
    if len(messages) <= 3:
        return messages  # nothing to trim

    # Keep system prompt(s) at the start and last 2 messages
    # Find how many leading system messages there are
    n_sys = 0
    for m in messages:
        if m.get("role") == "system":
            n_sys += 1
        else:
            break

    head = messages[:max(1, n_sys)]  # at least the first message
    tail = messages[-2:]  # last 2 messages
    middle = messages[max(1, n_sys):-2]

    # Drop middle messages from oldest first until we fit
    while middle and count_tokens(head + middle + tail) > max_tokens:
        dropped = middle.pop(0)
        role = dropped.get("role", "?")
        content = str(dropped.get("content", ""))[:50]
        print(f"[LocalLLM] \U0001F5D1 Dropped {role} message: {content}...")

    result = head + middle + tail
    final_count = count_tokens(result)
    if final_count > max_tokens:
        # Even with just head + tail it's too big — give up
        return None
    print(f"[LocalLLM] \u2702 Trimmed to {final_count} tokens ({len(result)} messages)")
    return result


def post_stream(messages, max_tokens, temperature=None, tools=None, timeout=(3, 120),
                reasoning=False, thinking_budget_tokens=0):
    """Low-level streaming POST to the local box. Returns the raw Response.

    thinking_budget_tokens: server-side cap on the thought channel. 0 = no
    thinking (speaking, summaries, vision, rewarm — the default), N = think up
    to N tokens then the server closes the tag and the model answers anyway.
    REQUIRES the server to run WITHOUT --reasoning-budget on the command line
    (per-request thinking_budget_tokens is only honored when the CLI value is
    the default -1) — see the launch command in the repo docs/notes.
    """
    payload = {
        "model": MODEL,
        "messages": messages,
        "stream": True,
        "temperature": DEFAULT_TEMP if temperature is None else temperature,
        "max_tokens": max_tokens,
        "cache_prompt": True,
        "thinking_budget_tokens": thinking_budget_tokens,
    }
    if reasoning:
        payload.update(REASONING_OVERRIDE_FIELDS)
    if tools:
        payload["tools"] = tools
    return SESSION.post(URL, json=payload, stream=True, timeout=timeout)


def iter_sse(resp):
    """Yield decoded JSON objects from an OpenAI-style SSE stream."""
    for raw in resp.iter_lines():
        if not raw:
            continue
        line = raw.decode("utf-8", "ignore")
        if not line.startswith("data: "):
            continue
        data_str = line[6:]
        if data_str == "[DONE]":
            break
        try:
            yield json.loads(data_str)
        except json.JSONDecodeError:
            continue


# Outcome of the most recent background request: True when it was aborted or
# the connection failed (used by rewarm() to know whether the cache is warm).
_last_bg_failed = {"value": False}


def _iter_sse_httpclient(resp):
    """Yield decoded JSON objects from an SSE stream on an http.client response."""
    while True:
        raw = resp.readline()
        if not raw:
            break
        line = raw.decode("utf-8", "ignore").strip()
        if not line.startswith("data: "):
            continue
        data_str = line[6:]
        if data_str == "[DONE]":
            break
        try:
            yield json.loads(data_str)
        except json.JSONDecodeError:
            continue


def generate_background(messages=None, prompt=None, image_b64=None,
                        max_tokens=512, temperature=0.6, tools=None,
                        reasoning=False, is_rewarm=False,
                        max_thinking_tokens=0, rewarm_hash=None):
    """
    Blocking text generation for shared background tasks (summary and vision).

    - Accepts either a full `messages` list or a single `prompt` string.
    - Optional `image_b64` is sent through the model's mmproj vision path.
    - `reasoning=True` re-enables thinking for an explicitly local reasoning call.
      Thinking output (delta.reasoning_content AND inline <think>/<|channel>thought
      blocks) is collected separately; if the model spends its entire budget
      thinking and produces no answer, the thinking text itself is returned as a
      salvage (callers can distill it) instead of a bogus empty result.
    - `max_thinking_tokens` (>0): hard cap on thinking deltas — when exceeded the
      stream is closed and whatever exists is returned (answer preferred,
      thinking as fallback).
    - Returns the generated text, or None if it was preempted / failed.

    Honors preempt_background(): if the user speaks mid-generation, this returns
    None promptly and the box is freed.

    After every non-rewarm background request (completed OR preempted), the
    speaking conversation's prefix is automatically re-warmed into the KV cache
    so the next user turn doesn't pay a cold prefill.
    """
    from tools_and_config.logger import debug

    # Conversation protection: while the user is actively talking, the single
    # SWA slot belongs to the speaking path — a background prompt here would
    # invalidate its cache/checkpoints and cost the next turn a full prefill.
    # Returning None makes generate_llm_resp fall back to the cloud.
    if not is_rewarm and conversation_hot():
        print("[LocalLLM] 🛡 Conversation is hot — refusing background request "
              "(caller should fall back to cloud).")
        return None

    # Preemptive context guard: if the prompt would blow the server's context
    # window, the request will 400. For non-rewarm background requests, try
    # to trim older messages (keeping system prompts and recent exchanges)
    # rather than sending a doomed request.
    if not is_rewarm and messages is not None:
        from core.brain.token_counter import would_exceed_context
        exceeds, tok_count = would_exceed_context(messages)
        if exceeds:
            print(f"[LocalLLM] ⚠ Background prompt too large ({tok_count} tokens) — "
                  f"trimming older messages to fit context.")
            messages = _emergency_trim_messages(messages, max_tokens=4500)
            if messages is None:
                print("[LocalLLM] ❌ Cannot trim prompt enough to fit context.")
                return None

    if messages is None:
        content = prompt or ""
        if image_b64:
            content = [
                {"type": "text", "text": prompt or ""},
                {"type": "image_url",
                 "image_url": {"url": f"data:image/jpeg;base64,{image_b64}"}},
            ]
        messages = [{"role": "user", "content": content}]

    try:
        with _bg_lock:
            # Re-check the warm hash UNDER the lock: two queued rewarms can both
            # pass the pre-lock check, then the second pointlessly re-prefills
            # what the first just warmed.
            if rewarm_hash is not None and _warm_prefix_hash["value"] == rewarm_hash:
                print("[LocalLLM] 🔥 Rewarm skipped (already warmed while queued).")
                return None
            _bg_abort.clear()
            _bg_active.set()
            _last_bg_failed["value"] = False
            conn = None
            resp = None
            text = ""
            thinking = ""
            thinking_deltas = 0
            finish_reason = None
            capped = False
            try:
                # Server-side thinking budget: N tokens of thought for reasoning
                # requests (the server closes the tag and the model still answers),
                # 0 for everything else. The client-side cap below stays as a
                # fallback for builds that ignore the per-request field.
                budget = (max_thinking_tokens or -1) if reasoning else 0
                payload = {
                    "model": MODEL,
                    "messages": messages,
                    "stream": True,
                    "temperature": DEFAULT_TEMP if temperature is None else temperature,
                    "max_tokens": max_tokens,
                    "cache_prompt": True,
                    "thinking_budget_tokens": budget,
                }
                if is_rewarm:
                    # Cache-warming request (rewarm / partial prefill): tell the
                    # box it may abort this decode MID-BATCH the instant a real
                    # request arrives — the socket preempt alone only takes
                    # effect at batch boundaries.
                    payload["internal_preemptible"] = True
                if reasoning:
                    payload.update(REASONING_OVERRIDE_FIELDS)
                if tools:
                    payload["tools"] = tools

                # Raw http.client connection (NOT requests): the socket is in
                # _bg_current from the instant the POST is sent, so a preempt
                # can hard-close it DURING prefill. With requests, the Response
                # only exists once headers arrive — which llama-server sends
                # after the entire prefill — making prefill un-abortable and
                # queueing the user's speaking request behind it (observed
                # ~55s time-to-first-word after a wake).
                conn = http.client.HTTPConnection(_HOST, _PORT, timeout=300)
                _bg_current["conn"] = conn
                if _bg_abort.is_set():  # preempted while we were acquiring the lock
                    _last_bg_failed["value"] = True
                    return None
                if not is_rewarm:
                    # A different prompt is about to occupy the single slot —
                    # the speaking prefix will no longer be warm.
                    _warm_prefix_hash["value"] = None
                conn.request("POST", _PATH, body=json.dumps(payload),
                             headers={"Content-Type": "application/json"})
                resp = conn.getresponse()  # blocks during prefill — abortable via socket
                if resp.status != 200:
                    body = resp.read(2000)
                    body_str = body.decode('utf-8', errors='replace') if isinstance(body, bytes) else str(body)
                    if 'exceed_context_size' in body_str:
                        print(f"[LocalLLM] \u274c Context size exceeded! Server rejected request. "
                              f"Auto-summarize should reduce context.")
                    raise RuntimeError(f"HTTP {resp.status}: {body_str[:300]!r}")
                for data in _iter_sse_httpclient(resp):
                    if _bg_abort.is_set():
                        print("[LocalLLM] Background task aborted mid-stream.")
                        _last_bg_failed["value"] = True
                        return None
                    choices = data.get("choices")
                    if not choices:
                        continue
                    finish_reason = choices[0].get("finish_reason") or finish_reason
                    delta = choices[0].get("delta", {}) or {}
                    rchunk = delta.get("reasoning_content") or ""
                    if rchunk:
                        thinking += rchunk
                        thinking_deltas += 1
                        # Fallback only: the server's thinking_budget_tokens should
                        # cap first; 1.5x headroom so we never kill a stream the
                        # server is capping correctly (delta count != exact tokens).
                        if max_thinking_tokens and thinking_deltas > max_thinking_tokens * 1.5 + 50:
                            capped = True
                            print(f"[LocalLLM] ⚠ Client thinking cap hit "
                                  f"(~{thinking_deltas} deltas > {max_thinking_tokens} budget; "
                                  f"server budget not enforced?) — closing stream.")
                            break
                    chunk = delta.get("content") or ""
                    if chunk:
                        text += chunk
                # Inline thinking (reasoning_format=none leaves it in content):
                # move it out of the answer into the thinking buffer.
                if reasoning or "<|channel>thought" in text or "<think" in text.lower():
                    for block in _THINK_BLOCK_RE.findall(text):
                        thinking += " " + block
                    tail = _THINK_OPEN_RE.search(strip_thinking_blocks_only(text))
                    if tail:
                        thinking += " " + tail.group(0)
                    text = strip_thinking(text)
                debug("LocalLLM", f"bg stream done: finish={finish_reason} capped={capped} "
                                  f"content={len(text)}ch thinking={len(thinking)}ch "
                                  f"({thinking_deltas} deltas) max_tokens={max_tokens}")
                if text.strip():
                    return text.strip()
                if thinking.strip():
                    # Model thought but never answered (budget spent thinking).
                    # Return the thinking itself so callers can salvage/distill it.
                    print(f"[LocalLLM] ⚠ No answer, only thinking ({len(thinking)} chars, "
                          f"finish={finish_reason}) — returning thinking text as salvage.")
                    debug("LocalLLM", f"thinking text: {thinking[:500]}...")
                    return strip_thinking(thinking).strip() or thinking.strip()
                if not is_rewarm:  # empty output is the NORMAL rewarm outcome
                    print(f"[LocalLLM] ⚠ Background request produced no output "
                          f"(finish={finish_reason}, max_tokens={max_tokens}).")
                return None
            except Exception as e:
                _last_bg_failed["value"] = True
                if _bg_abort.is_set():
                    print("[LocalLLM] Background task aborted (connection closed by preempt).")
                    return None
                print(f"[LocalLLM] Background generate failed: {e}")
                return None
            finally:
                _bg_current["conn"] = None
                _bg_active.clear()
                if rewarm_hash is not None and not _last_bg_failed["value"]:
                    # Rewarm completed (max_tokens=1 → empty output is normal):
                    # this prefix is now warm in the box's KV cache.
                    _warm_prefix_hash["value"] = rewarm_hash
                if conn is not None:
                    try:
                        conn.close()
                    except Exception:
                        pass
    finally:
        # Outside _bg_lock so the rewarm thread can acquire it immediately.
        if not is_rewarm:
            _schedule_rewarm()
