// Auto-generated by train_decision_tree.py -- DO NOT EDIT BY HAND
#ifndef ACTIVITY_TREE_H
#define ACTIVITY_TREE_H

typedef struct { int label; float confidence; } activity_result_t;

typedef enum {
    ACTIVITY_INACTIVE = 0,
    ACTIVITY_RESTING = 1,
    ACTIVITY_RUNNING = 2,
    ACTIVITY_TRANSITION = 3,
    ACTIVITY_WALKING = 4,
} activity_t;

static activity_result_t classify_activity(const float feat[6]) {
    // feature order: acc_mag_mean, gyro_mag_mean, acc_var, gyro_var, movement_intensity, acc_peak
    if (feat[4] <= 2.480701f) {
        if (feat[3] <= 0.204913f) {
            return (activity_result_t){ .label = ACTIVITY_INACTIVE, .confidence = 1.0000f };
        } else {
            return (activity_result_t){ .label = ACTIVITY_RESTING, .confidence = 1.0000f };
        }
    } else {
        if (feat[5] <= 1.784389f) {
            return (activity_result_t){ .label = ACTIVITY_WALKING, .confidence = 1.0000f };
        } else {
            if (feat[1] <= 66.526814f) {
                return (activity_result_t){ .label = ACTIVITY_RUNNING, .confidence = 0.7500f };
            } else {
                return (activity_result_t){ .label = ACTIVITY_RUNNING, .confidence = 1.0000f };
            }
        }
    }
}

#endif // ACTIVITY_TREE_H