// Auto-generated by train_cnn.py -- normalization constants (must match training)
#ifndef FALL_MODEL_NORM_H
#define FALL_MODEL_NORM_H

static const float FALL_MODEL_MEAN[6] = {0.000098f, 0.000105f, -0.000307f, -0.003593f, 0.010257f, -0.004118f};
static const float FALL_MODEL_STD[6]  = {0.760447f, 0.760293f, 0.760216f, 21.890240f, 21.908047f, 21.920401f};
#define FALL_MODEL_WINDOW_LEN 200
#define FALL_MODEL_N_CHANNELS 6

#endif // FALL_MODEL_NORM_H
