import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "tertiary-container": "var(--tertiary-container)",
        "error-container": "var(--error-container)",
        "surface-container-highest": "var(--surface-container-highest)",
        "tertiary": "var(--tertiary)",
        "primary-container": "var(--primary-container)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "on-primary-container": "var(--on-primary-container)",
        "surface-container-high": "var(--surface-container-high)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "inverse-primary": "var(--inverse-primary)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "surface": "var(--surface)",
        "on-surface-variant": "var(--on-surface-variant)",
        "glow-white": "var(--glow-white)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "surface-tint": "var(--surface-tint)",
        "calorie-green": "var(--calorie-green)",
        "surface-variant": "var(--surface-variant)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "error": "var(--error)",
        "secondary-container": "var(--secondary-container)",
        "on-error": "var(--on-error)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "surface-tertiary": "var(--surface-tertiary)",
        "heart-red": "var(--heart-red)",
        "outline-variant": "var(--outline-variant)",
        "on-background": "var(--on-background)",
        "secondary-fixed": "var(--secondary-fixed)",
        "on-surface": "var(--on-surface)",
        "surface-dim": "var(--surface-dim)",
        "on-tertiary": "var(--on-tertiary)",
        "inverse-surface": "var(--inverse-surface)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "outline": "var(--outline)",
        "border-subtle": "var(--border-subtle)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "on-secondary-container": "var(--on-secondary-container)",
        "surface-bright": "var(--surface-bright)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "surface-container-low": "var(--surface-container-low)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "on-primary": "var(--on-primary)",
        "on-error-container": "var(--on-error-container)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "step-blue": "var(--step-blue)",
        "primary-fixed": "var(--primary-fixed)",
        "background": "var(--background)",
        "secondary": "var(--secondary)",
        "on-secondary": "var(--on-secondary)",
        "primary": "var(--primary)",
        "surface-container": "var(--surface-container)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "section-gap": "3rem",
        "inner-padding": "1.25rem",
        "gutter": "1rem",
        "group-gap": "1.5rem",
        "metric-inset": "2rem"
      },
      fontFamily: {
        "label-caps": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "display-metric": ["Hanken Grotesk"],
        "headline-sm": ["Hanken Grotesk"],
        "body-md": ["Inter"],
        "display-metric-mobile": ["Hanken Grotesk"],
        "data-point": ["Hanken Grotesk"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-metric": ["64px", { lineHeight: "72px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-metric-mobile": ["48px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "data-point": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
};
export default config;
